/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';
import { LiWEResponse, sendParametersError, sendResponse } from '../../liwe/response';

import {
	// endpoints function
	delete_userlogin_del, get_userlogin_clear, get_userlogin_list,
	// functions
	
} from './methods';

import {
	UserLoginLog, UserLoginLogKeys, UserLoginLogPublic, UserLoginLogPublicKeys,
} from './types';

/*=== f2c_start __header ===*/
import { userlogin_db_init } from './methods';
/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - userlogin " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "userlogin", l ) );
	userlogin_db_init ( liwe );

	app.get ( '/api/userlogin/list', perms( [ "userlogin.list" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { action, rows, skip, ___errors } = typed_dict( req.query as any, [
			{ name: "action", type: "string" },
			{ name: "rows", type: "number" },
			{ name: "skip", type: "number" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_userlogin_list ( req, action, rows, skip);
		sendResponse ( res, response );
	} );

	app.get ( '/api/userlogin/clear', perms( [ "userlogin.clear" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_userlogin_clear ( req, );
		sendResponse ( res, response );
	} );

	app.delete ( '/api/userlogin/del', perms( [ "userlogin.clear" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_userlogin_del ( req, id);
		sendResponse ( res, response );
	} );

};
