/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"userlogin.list": "Can  list login logs",
	"userlogin.clear": "Can clear login logs",
};

export default permissions;
